//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessAssistant.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeWorkout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeWorkout()
        {
            this.Workout = new HashSet<Workout>();
        }
    
        public int IdTypeWorkout { get; set; }
        public string NameTypeWorkout { get; set; }
        public double CalorieConsumptionRatio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workout> Workout { get; set; }
    }
}
