//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessAssistant.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWorkout
    {
        public int IdUserWorkout { get; set; }
        public int IdUser { get; set; }
        public int IdWorkout { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
