//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessAssistant.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWorkout
    {
        public int IdUserWorkout { get; set; }
        public int IdUser { get; set; }
        public Nullable<System.DateTime> DateWorkout { get; set; }
        public Nullable<int> DurationWorkout { get; set; }
        public Nullable<int> IdTypeWorkout { get; set; }
    
        public virtual TypeWorkout TypeWorkout { get; set; }
        public virtual Users Users { get; set; }
    }
}
